// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3WHZn2JnFnUTi3nTVRJnVWHKQONsoE7w',
    appId: '1:585306867664:web:d61d08920804b95fb2dbd5',
    messagingSenderId: '585306867664',
    projectId: 'chat-c0e2b',
    authDomain: 'chat-c0e2b.firebaseapp.com',
    storageBucket: 'chat-c0e2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEhgON99KLIrnx9hn_jYEp01iJRRVN7cc',
    appId: '1:585306867664:android:682ff5bed2f69e72b2dbd5',
    messagingSenderId: '585306867664',
    projectId: 'chat-c0e2b',
    storageBucket: 'chat-c0e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMQkrKPN_M7wPvcznFrjNwPixp7i9-gg',
    appId: '1:585306867664:ios:88b976d385b3e49db2dbd5',
    messagingSenderId: '585306867664',
    projectId: 'chat-c0e2b',
    storageBucket: 'chat-c0e2b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTMQkrKPN_M7wPvcznFrjNwPixp7i9-gg',
    appId: '1:585306867664:ios:88b976d385b3e49db2dbd5',
    messagingSenderId: '585306867664',
    projectId: 'chat-c0e2b',
    storageBucket: 'chat-c0e2b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3WHZn2JnFnUTi3nTVRJnVWHKQONsoE7w',
    appId: '1:585306867664:web:bed3d629d50ec187b2dbd5',
    messagingSenderId: '585306867664',
    projectId: 'chat-c0e2b',
    authDomain: 'chat-c0e2b.firebaseapp.com',
    storageBucket: 'chat-c0e2b.appspot.com',
  );
}
